import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diffrun Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const clerkKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  if (!clerkKey) {
    throw new Error("NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is not defined");
  }
  return (
    <html lang="en">
      <body>
        <Script
          src="https://unpkg.com/@clerk/clerk-js@latest/dist/clerk.browser.js"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
          data-clerk-publishable-key={clerkKey}
          data-clerk-frontend-api="knowing-macaque-84.clerk.accounts.dev"
        />

        {children}
      </body>
    </html>
  );
}